spring.application.name=bookstore-backend
# H2 Database Configuration (Not Persistent Local Disk)
spring.datasource.url=jdbc:h2:mem:bookstore;FILE_LOCK=NO
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Optional: Enables the H2 Web Console at http://localhost:8080/h2-console
spring.h2.console.enabled=true

# Enable SQL initialization
spring.sql.init.mode=always

# Specify the path to your schema script (optional if named schema.sql)
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql