spring.application.name=bookstore-backend
spring.datasource.url=jdbc:h2:mem:bookstore;FILE_LOCK=NO
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# Optional: Enables the H2 Web Console at http://localhost:8080/h2-console
spring.h2.console.enabled=true
# Enable SQL initialization
spring.sql.init.mode=always
# Specify the path to your schema script (optional if named schema.sql)
spring.sql.init.schema-locations=classpath:app-schema.sql
spring.sql.init.data-locations=classpath:app-data.sql
# https://math.mit.edu/~gs/linearalgebra/ila5/linearalgebra5_Front.jpg

# JWT Configuration
jwt.secret=mySecretKeyForJwtTokenGenerationAndValidation1234567890
jwt.expiration=3600